function PH_DisplayControls(varargin)
	
	% Print controls
	CreateStruct.Interpreter = 'tex';
	CreateStruct.WindowStyle = 'non-modal';
	msgbox( ...
		{'\fontsize{12}' ...
		'\bfTip: If the GUI is slow, try turning off the atlas slice (s)\rm' ...
		'' ...
		'\bf Probe: \rm' ...
		'Arrow keys : translate probe' ...
		'Alt/Option up/down : raise/lower probe' ...
		'Alt/Option left/right : shrink/stretch probe' ...
		'Shift arrow keys : change probe angle' ...
		'Shift +/- : change step size' ...
		'm : set probe location manually', ...
		'\bf 3D brain areas: \rm' ...
		' =/+ : add (list selector)' ...
		' Alt/Option =/+ : add (search)' ...
		' Control =/+ : add (hierarchy selector)' ...
		' - : remove', ...
		'\bf Visibility: \rm' ...
		's : atlas slice (toggle tv/av/off)' ...
		'b : brain outline' ...
		'p : probe' ...
		'a : 3D brain areas' ...
		'\bf Other: \rm' ...
		'x : export probe coordinates to workspace' ...
		'h : load and plot histology-defined trajectory', ...
		'F1 : bring up this window'}, ...
		'Controls',CreateStruct);
	
end


