function PH_HelloWorld(varargin)

	% Print controls
	CreateStruct.Interpreter = 'tex';
	CreateStruct.WindowStyle = 'non-modal';
	cellTxt = {'\fontsize{12}' ...
		'\bfv1.1 updates\rm' ...
		'I added several new features since v1, so I' ...
		'recommend you check the manual:' ...
		'' ...
		'' ...
		'' ...
		'\bfImportant note on cluster indexing: \rm' ...
		'As of version 1.1 (March 2024) the ProbeFinder' ...
		'uses cluster\_id indexing identical to that of' ...
		'Kilosort and any .tsv files in your ephys path.' ...
		'This makes more sense, but means you should' ...
		'double-check you are not adding a +1 somewhere' ...
		'in your pipeline to correct for 0 vs 1 indexing' ...
		'that was necessary in v1.0.'...
		'' ...
		'\bfIf anything is bugging you...\rm' ...
		'If you find any bugs, please leave me a message'...
		'at the GitHub repository and I will take a look.'...
		''...
		'Happy ProbeFinding!'...
		' - Jorrit Montijn'};
	
	hMsgBox = msgbox( ...
		cellTxt, ...
		'Welcome to the ProbeFinder!',CreateStruct);
	
	%add link to manual
	vecPos = [0 (1 - 5/numel(cellTxt)) 1 1/numel(cellTxt)];
	hAx = axes(hMsgBox,'Position',vecPos);
	axis(hAx,'off');
	hTxt = text(hAx,0.9,0.5,'$\mathrm{\underline{UserGuide\_UniversalProbeFinder\_v1.1.pdf}}$',...
		'color',[0 0 .8],'FontSize',12,'Interpreter','latex',...
		'HorizontalAlignment','right');
	hTxt.ButtonDownFcn = @(~,~)web('https://github.com/JorritMontijn/UniversalProbeFinder/blob/main/UserGuide_UniversalProbeFinder_v1.1.pdf'); % this opens the website

end


